{"name": "Test  To View LeaveList To Employee", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: Element <input id=\"leaveList_chkSearchFilter_checkboxgroup_allcheck\" type=\"checkbox\"> is not clickable at point (212, 332). Other element would receive the click: <a class=\"ui-datepicker-prev ui-corner-all\" data-handler=\"prev\" data-event=\"click\" title=\"Prev\">...</a>\n  (Session info: chrome=80.0.3987.149)\n  (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 5.3.0-28-generic x86_64)\n\n", "trace": "  File \"/home/priyanka/Desktop/virtualenv/sample_POM/lib/python3.6/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/priyanka/Desktop/virtualenv/sample_POM/lib/python3.6/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/leavelist.py\", line 22, in step_impl\n    context.leavelist.set_show_leave_with_status()\n  File \"/home/priyanka/Desktop/First_Project_BDD_POM_Revised_phase2/First_Project/features/pages/leavelist.py\", line 27, in set_show_leave_with_status\n    return self.driver.find_element_by_xpath(self.show_leave_with_status_all_xpath).click()\n  File \"/home/priyanka/Desktop/virtualenv/sample_POM/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py\", line 80, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"/home/priyanka/Desktop/virtualenv/sample_POM/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n    return self._parent.execute(command, params)\n  File \"/home/priyanka/Desktop/virtualenv/sample_POM/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"/home/priyanka/Desktop/virtualenv/sample_POM/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given I login to the OrangeHRMS", "status": "passed", "start": 1593148261033, "stop": 1593148263638}, {"name": "When I click on the \"Leave\"", "status": "passed", "start": 1593148263639, "stop": 1593148265998}, {"name": "And I fill the fields to view leavelist table", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: Element <input id=\"leaveList_chkSearchFilter_checkboxgroup_allcheck\" type=\"checkbox\"> is not clickable at point (212, 332). Other element would receive the click: <a class=\"ui-datepicker-prev ui-corner-all\" data-handler=\"prev\" data-event=\"click\" title=\"Prev\">...</a>\n  (Session info: chrome=80.0.3987.149)\n  (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 5.3.0-28-generic x86_64)\n\n", "trace": "  File \"/home/priyanka/Desktop/virtualenv/sample_POM/lib/python3.6/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/priyanka/Desktop/virtualenv/sample_POM/lib/python3.6/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/leavelist.py\", line 22, in step_impl\n    context.leavelist.set_show_leave_with_status()\n  File \"/home/priyanka/Desktop/First_Project_BDD_POM_Revised_phase2/First_Project/features/pages/leavelist.py\", line 27, in set_show_leave_with_status\n    return self.driver.find_element_by_xpath(self.show_leave_with_status_all_xpath).click()\n  File \"/home/priyanka/Desktop/virtualenv/sample_POM/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py\", line 80, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"/home/priyanka/Desktop/virtualenv/sample_POM/lib/python3.6/site-packages/selenium/webdriver/remote/webelement.py\", line 633, in _execute\n    return self._parent.execute(command, params)\n  File \"/home/priyanka/Desktop/virtualenv/sample_POM/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"/home/priyanka/Desktop/virtualenv/sample_POM/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1593148265998, "stop": 1593148266566}, {"name": "Then I must navigate to the LeaveList page", "status": "skipped", "start": 1593148266567, "stop": 1593148266567}], "start": 1593148261033, "stop": 1593148266567, "uuid": "2f67cde4-8096-464a-91f0-846d298bf77f", "historyId": "5fbdfc9d543fa1431ce0cec5fc6bd1f0", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "List Of leave Of an employee"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}